/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaprojekt;

/**
 *
 * @author theph
 */
public class AddItems extends javax.swing.JFrame {

    /**
     * Creates new form AddItems
     */
    public AddItems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j1stTypeTextBox = new javax.swing.JTextField();
        j2ndtTypeTextBox = new javax.swing.JTextField();
        j3rdTypeTextBox = new javax.swing.JTextField();
        jNameLabel1 = new javax.swing.JLabel();
        jNameLabel2 = new javax.swing.JLabel();
        jNameLabel3 = new javax.swing.JLabel();
        jNameLabel4 = new javax.swing.JLabel();
        j3rdTypeTextBox1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j1stTypeTextBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        j1stTypeTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1stTypeTextBoxMouseClicked(evt);
            }
        });

        j2ndtTypeTextBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        j2ndtTypeTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2ndtTypeTextBoxMouseClicked(evt);
            }
        });

        j3rdTypeTextBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        j3rdTypeTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3rdTypeTextBoxMouseClicked(evt);
            }
        });

        jNameLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jNameLabel1.setText("Name:");

        jNameLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jNameLabel2.setText("Name:");

        jNameLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jNameLabel3.setText("Name:");

        jNameLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jNameLabel4.setText("Name:");

        j3rdTypeTextBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        j3rdTypeTextBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3rdTypeTextBox1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNameLabel1)
                    .addComponent(jNameLabel2)
                    .addComponent(jNameLabel3)
                    .addComponent(jNameLabel4))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j3rdTypeTextBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(j2ndtTypeTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(j3rdTypeTextBox)
                        .addComponent(j1stTypeTextBox)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1stTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j3rdTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2ndtTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameLabel4)
                    .addComponent(j3rdTypeTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j1stTypeTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1stTypeTextBoxMouseClicked
        j1stTypeTextBox.setText(null);
    }//GEN-LAST:event_j1stTypeTextBoxMouseClicked

    private void j2ndtTypeTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2ndtTypeTextBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ndtTypeTextBoxMouseClicked

    private void j3rdTypeTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3rdTypeTextBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_j3rdTypeTextBoxMouseClicked

    private void j3rdTypeTextBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3rdTypeTextBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_j3rdTypeTextBox1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField j1stTypeTextBox;
    private javax.swing.JTextField j2ndtTypeTextBox;
    private javax.swing.JTextField j3rdTypeTextBox;
    private javax.swing.JTextField j3rdTypeTextBox1;
    private javax.swing.JLabel jNameLabel1;
    private javax.swing.JLabel jNameLabel2;
    private javax.swing.JLabel jNameLabel3;
    private javax.swing.JLabel jNameLabel4;
    // End of variables declaration//GEN-END:variables
}
